### ISSUE TITLE
Can not make it work on my computer.

### ISSUE THREAD

**Issue by zhujingx** [Esri/workflowmanager-dashboard-samples#1]
I can not make it work on my computer, I could not add create job widget, Job widget, and the Report widget. I got Connection refused error, other widget like the chart widget pie widget are fine.

Do you know why this happened?

Thanks

**Comment by kbedel** [comment]
Hi. What mode were you using to deploy the widgets? Were you testing them in DevMode, or fully deployed them? Are you pointing to an internal Workflow Manager server or just trying to get it working with the sample service as it is in the settings.js file in the repository? As well, are you trying to run this in the browser or in the desktop Operations Dashboard application?

**Comment by zhujingx** [comment]
I Used the dev mode. But I got the connection refused error. I only try to use the sample from ESRI not my own map service or workflow sevice.
Thanks
Zhujing



[cid:image001.png@01D3287D.6275D9B0]

**Comment by kbedel** [comment]
I did not receive a connection refused error, but I did find a few issues in the widgets which I have repaired. The updated version should work in dev mode with the sample service without modification.

**Comment by zhujingx** [comment]
I still go the connection refused the error, is that because my web server is not public server? which is inside the fire wall only can be access by inside our organization.

**Comment by kbedel** [comment]
I would recommend trying to use the [debugging functionality](https://developers.arcgis.com/javascript/3/jshelp/operations-dashboard-extensibility-test-debug.html) provided by Operations Dashboard to see what is going on. It should provide info about what calls are being made to the server, as well as which one(s) are failing. Once you have that info, you may be able to try the same call from your browser and see if it is also blocked.

**Comment by zhujingx** [comment]
The debug tool got the same error and there is no further link or message

[cid:image002.jpg@01D32BDA.EA831380]

**Comment by kbedel** [comment]
Where are you getting this error message? Does the network tab of the debugging tools have any additional information? Would it be possible to include some screenshots?

**Comment by zhujingx** [comment]
I only have ‘Open Debug Tool” option the Open in Browser option is gray out. See the first screen shot.
After I click on the Open Debug Tool It sees the error message already before I add in the widget. See screen shot 2. There is no network tab or any thing.

[cid:image001.png@01D32BDD.925ECED0]



[cid:image002.png@01D32BDD.925ECED0]From: Kevin Bedel [mailto:notifications@github.com]
Sent: Tuesday, September 12, 2017 3:37 PM
To: Esri/workflowmanager-dashboard-samples <workflowmanager-dashboard-samples@noreply.github.com>
Cc: Xia, Zhujing <ZhujingX@co.rockland.ny.us>; Author <author@noreply.github.com>
Subject: Re: [Esri/workflowmanager-dashboard-samples] Can not make it work on my computer. (#1)



ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.



Where are you getting this error message? Does the network tab of the debugging tools have any additional information? Would it be possible to include some screenshots?

**Comment by kbedel** [comment]
The screenshots are not being attached to the issue. Can you adding them from the website rather than replying via e-mail?

**Comment by zhujingx** [comment]
I only have ‘Open Debug Tool” option the Open in Browser option is gray out. See the first screen shot.
After I click on the Open Debug Tool It sees the error message already before I add in the widget. See screen shot 2. There is no network tab or any thing.
![dashboard_1](https://user-images.githubusercontent.com/19692323/30345200-38483704-97d2-11e7-9c7a-7f7329329e37.png)
![dashboard_2](https://user-images.githubusercontent.com/19692323/30345211-40982e78-97d2-11e7-8c3f-5ffa0cf3f2c3.png)

**Comment by kbedel** [comment]
OK, these seems to be an issue with Operations Dashboard itself rather than the Workflow Manager widgets. I would recommend contacting Esri Technical Support or the [Operation Dashboard Geonet Community](https://geonet.esri.com/community/gis/applications/operations-dashboard-for-arcgis) for more assistance.

**Comment by zhujingx** [comment]
Thanks I will do that.
